general.import = [
   "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[terminal.shell]
args = ["new-session"]
program = "/usr/bin/tmux"

[window]
padding.x = 0
padding.y = 10
dynamic_padding = true
startup_mode = "Maximized"
decorations = "none"
opacity= 0.86

[colors]
primary.background = "#000000"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12.5

[terminal]
